---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
knitr::opts_knit$set(root.dir = tempdir())  # Only affects code execution, not output
```

# ducklake

ducklake is an R package which complements the existing toolkits in the [duckdb](https://r.duckdb.org/index.html) and [duckplyr](https://duckplyr.tidyverse.org/index.html) packages, in order to support the new [DuckLake](https://ducklake.select/docs/stable/duckdb/introduction.html) ecosystem.

## Installation

Install the development version of ducklake with

``` r
pak::pak("tgerke/ducklake")
```

## Create a local duckdb lakehouse

```{r example}
library(ducklake)

# install the ducklake extension to duckdb 
# requires that you already have DuckDB v1.3.0 or higher
install_ducklake()

# set up a temporary directory to demonstrate use
temp_dir <- tempdir()
# haha Jenny Bryan is going to set my computer on fire
setwd(temp_dir)

# create the ducklake
attach_ducklake("my_ducklake")
# show that we have ducklake files
list.files()

# create a table using the Netherlands train traffic dataset 
create_table("nl_train_stations", "https://blobs.duckdb.org/nl_stations.csv")
# show that we now have a .files directory
list.files()
# main/ is where the parquet files go
list.files("my_ducklake.ducklake.files/main/")

# connect to the ducklake
con <- duckdb::dbConnect(
  duckdb::duckdb(
    dbdir = paste0(temp_dir, "/my_ducklake.ducklake"),
    read_only = FALSE
  )
)

# list tables in the metadata store
duckdb::dbListTables(con)
```

This next section is dev/WIP! 
```{r}
library(duckplyr)

# try to get to the nl_train_stations table
duckplyr::db_exec("USE my_ducklake;")
query_result <- DBI::dbGetQuery(con, "SELECT * FROM ducklake_table WHERE table_name = 'nl_train_stations';")
query_result
duckplyr::as_duckdb_tibble(query_result)

DBI::dbGetQuery(con, "SELECT * FROM ducklake_schema WHERE schema_id = 0;")
# this is still just metadata
DBI::dbGetQuery(con, "SELECT * FROM ducklake_column WHERE table_id = 1;")

# there doesn't seem to be a direct way to reference the nl_train_stations table with existing duckplyr resources
# I believe this is because of the nested/heirarchical nature of ducklake
# So, get the data path and file name
data_path <- DBI::dbGetQuery(con, "SELECT value FROM ducklake_metadata WHERE key = 'data_path'")$value
train_data <- DBI::dbGetQuery(con, "SELECT * FROM ducklake_data_file WHERE table_id = 1;")
file_name <- train_data$path
full_path <- paste0(data_path, "main/nl_train_stations/", file_name)

# Now try to read with the full path
train_stations <- DBI::dbGetQuery(con, sprintf("SELECT * FROM parquet_scan('%s')", full_path))

# Convert to duckplyr tibble
nl_train_stations <- duckplyr::as_duckdb_tibble(train_stations)
nl_train_stations

# First make sure we're in the right schema
duckplyr::db_exec("USE my_ducklake;")

# Show current value
nl_train_stations |> filter(code == "ASB")

# Make the update using duckplyr syntax
nl_train_stations_new <- nl_train_stations |> 
  mutate(
    name_long = case_when(
      code == "ASB" ~ "Johan Cruijff ArenA",
      .default = name_long
    )
  ) |> 
  compute()

# Check the change
nl_train_stations_new |> filter(code == "ASB")

# Register the modified table back to DuckLake
duckdb::duckdb_register(con, "temp_stations", nl_train_stations_new)
duckplyr::db_exec("CREATE OR REPLACE TABLE my_ducklake.nl_train_stations AS SELECT * FROM temp_stations;")

# Check the snapshots after the update
DBI::dbGetQuery(con, "SELECT * FROM ducklake_snapshot ORDER BY snapshot_id;")

# Look at the changes between snapshots
DBI::dbGetQuery(con, "SELECT * FROM ducklake_snapshot_changes WHERE snapshot_id = 2;")

# Look at the data files and their snapshots
DBI::dbGetQuery(con, "
  SELECT d.*, s.snapshot_time 
  FROM ducklake_data_file d 
  JOIN ducklake_snapshot s ON d.begin_snapshot = s.snapshot_id 
  WHERE d.table_id = 1 
  ORDER BY d.begin_snapshot;
")

```

